# Implementação da matriz de rotação de givens

O código exemplo mostra todas as formas da matriz de givens

In [14]:
import givens
from itertools import combinations
from numpy import pi

# Tamanho
SIZE = 5

# Angulo 
THETA = pi/6

# Exemplo de código para combinações possíveis de uma matriz de givens

for i,j in combinations(xrange(SIZE),2):
    print givens.givens(i,j,THETA,SIZE)
    print 

[[ 0.8660254  0.5        0.         0.         0.       ]
 [-0.5        0.8660254  0.         0.         0.       ]
 [ 0.         0.         1.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]
 [ 0.         0.         0.         0.         1.       ]]

[[ 0.8660254  0.         0.5        0.         0.       ]
 [ 0.         1.         0.         0.         0.       ]
 [-0.5        0.         0.8660254  0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]
 [ 0.         0.         0.         0.         1.       ]]

[[ 0.8660254  0.         0.         0.5        0.       ]
 [ 0.         1.         0.         0.         0.       ]
 [ 0.         0.         1.         0.         0.       ]
 [-0.5        0.         0.         0.8660254  0.       ]
 [ 0.         0.         0.         0.         1.       ]]

[[ 0.8660254  0.         0.         0.         0.5      ]
 [ 0.         1.         0.         0.         0.       ]
 [ 0.   

In [4]:
def float_to_precision(num,prec=24):
    exp = -np.floor(np.log2(num))
    n2 = num*2**(exp)
    n3 = int(n2*2**prec)
    return (float(n3)/(2**prec)/(2**exp))

val = 10.93482948572093485792384579238450284752394857
print val,float_to_precision(val)

10.9348294857 10.9348292351


In [6]:
from numpy.linalg import svd
import numpy as np

A = np.matrix([[0x00,0xff,0x00],[0xff,0x00,0x00],[0x00,0x00,0xFF]])
A2 = np.matrix([[0x00,0xff,0x00],[0xff,0x00,0x00],[0x00,0x00,0xFF]])
print A
U, s, V = svd(A)

#recuperar A:
S = np.diag(s)
np.allclose(A2, np.dot(U, np.dot(S, V)))

print A2

[[  0 255   0]
 [255   0   0]
 [  0   0 255]]
[[  0 255   0]
 [255   0   0]
 [  0   0 255]]


In [3]:
import random

MATRIX_SIZE = 128 # 24 bits

A = [[random.randint(0,2**24) for __ in xrange(MATRIX_SIZE)] for _ in xrange(MATRIX_SIZE)]

A = np.matrix(A)

set_float_prec = np.vectorize(float_to_precision)

print A

U, s, V = svd(A)
S = np.diag(set_float_prec(s,prec = 8))
A2 = np.dot(U, np.dot(S, V))



print (A2 - A)/A

NameError: name 'float_to_precision' is not defined

In [136]:
#teste com uma imagem
from IPython.display import Image

import dimage
reload(dimage)

img = dimage.DanImg(bmp="rainbow128.bmp")

#print img.pix

pixelmap24 = img.pix24

pm24 = np.matrix(pixelmap24)

set_float_prec = np.vectorize(float_to_precision)
to_integer_matrix = np.vectorize(int)

U, s, V = svd(pm24)

precisions = [52,36,23,16,8]

for prec in precisions:
    S = np.diag(set_float_prec(s,prec = prec))
    # S = np.diag(s)
    pm24_2 = to_integer_matrix(np.dot(U, np.dot(S, V)))
    E
    #print str(pm24_2)
    #print str(pm24)
    
    img.pix_from_pix24(pm24_2.tolist())
    img.rec_bmp_from_pix("teste%02u.bmp"%(prec))


138 128 128 49290 16384 3


In [5]:
#teste com uma imagem
from IPython.display import Image

import dimage
import numpy as np
reload(dimage)

img = dimage.DanImg(bmp="rainbow128.bmp")

#print img.pix

pixelmap24 = img.pix24

pm24 = np.matrix(pixelmap24)

set_float_prec = np.vectorize(float_to_precision)
to_integer_matrix = np.vectorize(int)

U, s, V = svd(pm24)

precisions = [52,36,23,16,8]



for prec in precisions:
    S = np.diag(set_float_prec(s,prec = prec))
    # S = np.diag(s)
    pm24_2 = to_integer_matrix(np.dot(U, np.dot(S, V)))
    E
    #print str(pm24_2)
    #print str(pm24)
    
    img.pix_from_pix24(pm24_2.tolist())
    img.rec_bmp_from_pix("teste%02u.bmp"%(prec))

138 128 128 49290 16384 3


NameError: name 'svd' is not defined

Original:
<img src="rainbow128.bmp">
52 bits
<img src="teste52.bmp">
36 bits
<img src="teste36.bmp">
23 bits
<img src="teste23.bmp">
16 bits
<img src="teste16.bmp">
8 bits
<img src="teste08.bmp">

In [ ]:
import numpy as np
import givens
import itertools
from itertools import combinations

NUMBER_OF_ANGLES = 36

MATRIX_SIZE = 10

ANGLES = np.arange(0,2*np.pi,2*np.pi/NUMBER_OF_ANGLES)

ANGS_TABLE = {}

for ang in ANGLES:
    ANGS_TABLE[ang] = np.identity(MATRIX_SIZE)
    for i,j in combinations(xrange(MATRIX_SIZE),2):
        ANGS_TABLE[ang] = np.dot(ANGS_TABLE[ang],givens.givens(i,j,ang,MATRIX_SIZE))
    #print ang,ANGS_TABLE[ang]

LTABLE = {}

for angs in itertools.product(ANGS_TABLE,repeat=MATRIX_SIZE-1):
    #print angs
    MAT = np.identity(MATRIX_SIZE)
    for ang in angs:
        MAT = np.dot(MAT,ANGS_TABLE[ang])
    LTABLE[angs] = MAT
    
print len(ANGS_TABLE), len(LTABLE)

In [4]:
36**4

1679616